apiVersion: v1
kind: Service
metadata:
  name: coding-dojo
  labels:
    app: coding-dojo
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: coding-dojo
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: coding-dojo
  labels:
    app: coding-dojo
spec:
  selector:
    matchLabels:
      app: coding-dojo
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: coding-dojo
        tier: frontend
    spec:
      containers:
      - image: gcr.io/coding-dojo-251421/coding-dojo:0.1.0
        name: coding-dojo
        env:
        ports:
        - containerPort: 3000
          name: coding-dojo
